name: Sync dev to main

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: write # to push to main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          path: dev
      - name: Setup Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Install dependency
        run: npm install fast-glob fs-extra

      - uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: ".does_not_exist"
          sparse-checkout-cone-mode: false
          path: main

      - name: Sync and commit files
        run: node dev/.github/workflows/sync.ts
