name: Sync dev to main & CI Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: write # to push to main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev
        uses: actions/checkout@v6
        with:
          ref: dev
          path: dev
          fetch-depth: 1

      - name: Checkout main
        uses: actions/checkout@v6
        with:
          ref: main
          path: main
          fetch-depth: 1
          
      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Dependency
        run: npm install fast-glob fs-extra @google/genai

      - name: Translate modified readme files
        run: node dev/.github/workflows/scripts/translate.ts
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Sync and commit files
        run: node dev/.github/workflows/sync.ts main dev dev/sync-list.json
      
      - name: Install Dependency
        run: cp dev/package-lock.json main && cp -r dev/ref main && cd main && mkdir dist && npm ci
          
      - name: Run tests
        uses: Wu-Yijun/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/.github/actions/CI@dev
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          path: main/dist
          name: test_output
      
      - name: Panic on Test Errors
        run: |
          # Check if main/dist/failed_list.txt is empty
          if [ -s main/dist/failed_list.txt ]; then
            cat main/dist/failed_list.txt
            echo "Abort Workflow to Send Notification"
            exit 1
          fi
        # continue-on-error: true